### ISSUE TITLE
What is this JSON parse bug?

### ISSUE THREAD

**Issue by pavellishin** [pavellishin/slackidlerpg#54]
```
info: Sent message to T0HE0MF52:C7JCG4FV3: User <@U0JULDCGH> penalized *5 minutes, 44 seconds* for message. New time to level 35: *9 hours, 15 minutes, 19 seconds*.

Unhandled rejection SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at storage.get.then (/Users/pavel.lishin/projects/slackidlerpg/src/idle.js:104:30)
```

Probably related to #46. I need to rethink storage, anyway - I shouldn't have to know what keys return what data types, `Storage` shouldn't be a dumb store, it should be something to make slackidlerpg easier to develop.

Probably also a symptom of #28.

**Comment by pavellishin** [comment]
More information:

```
error:  SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at storage.get.then (/Users/pavel.lishin/projects/slackidlerpg/src/idle.js:107:32)
    at tryCatcher (/Users/pavel.lishin/projects/slackidlerpg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/pavel.lishin/projects/slackidlerpg/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/pavel.lishin/projects/slackidlerpg/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/pavel.lishin/projects/slackidlerpg/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/pavel.lishin/projects/slackidlerpg/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/pavel.lishin/projects/slackidlerpg/node_modules/bluebird/js/release/promise.js:636:18)
    at Multi.callback (/Users/pavel.lishin/projects/slackidlerpg/node_modules/bluebird/js/release/nodeback.js:42:21)
    at multi_callback (/Users/pavel.lishin/projects/slackidlerpg/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/Users/pavel.lishin/projects/slackidlerpg/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/Users/pavel.lishin/projects/slackidlerpg/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/Users/pavel.lishin/projects/slackidlerpg/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.returnReply (/Users/pavel.lishin/projects/slackidlerpg/node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/Users/pavel.lishin/projects/slackidlerpg/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/Users/pavel.lishin/projects/slackidlerpg/node_modules/redis/index.js:267:27)
error: Unable to parse data for player T0HE0MF52:undefined: undefined
```

**Comment by pavellishin** [comment]
So it looks like some event comes through to `handleEvent` where I cannot get the player_id.

Should really finish the event extraction.
